phpcs:
  files: src/
  standards: [PSR1, PSR2]
phpmd:
  files: src/
pdepend:
  files: src/
function_blacklist:
  files: src/
  blacklist:
    die: notice
    echo: notice
    var_dump: error
comment_blacklist:
  files: src/
  blacklist:
    todo: notice
    "dont commit": error
doc_block:
  files: src/
  missing_docblock: error
  missing_newline_before_return: notice
  obsolete_variable: notice
  missing_variable: notice
  missing_type_in_docblock: notice
  missing_type_in_signature: notice
  type_missmatch: notice
