language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - nightly
  - hhvm
  - hhvm-nightly
  
matrix:
  allow_failures:
    - php: 7
    - php: nightly
    - php: hhvm
    - php: hhvm-nightly

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""
  
before_script:
    - composer self-update
    - composer update --prefer-source $PREFER_LOWEST

script: phpunit

after_success: bin/simpspector ./ -f detail
