language: php

sudo: false

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

before_script:
    - travis_retry composer self-update
    - travis_retry composer update $PREFER_LOWEST
    - curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
    - chmod +x phpcs.phar
    - sed -i -e 's/\"phpcs\"/\"\.\/phpcs\.phar\"/g' config/parameters.dist.yml

script:
    - bin/phpunit
    - bin/simpspector analyse ./ -v -f detail