language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: 7
    - php: nightly
    - php: hhvm

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

before_script:
    - travis_retry composer self-update
    - travis_retry composer update $PREFER_LOWEST

script:
    - bin/phpunit
    - bin/simpspector analyse ./ -v -f detail
